# Generated by Django 3.1.2 on 2020-11-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_liked_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_user',
            new_name='liked_users',
        ),
    ]
