# Generated by Django 3.1.2 on 2020-11-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201103_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgage',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
