# Generated by Django 3.1.2 on 2020-11-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgage',
            new_name='image',
        ),
    ]
